# Site settings
title: 
email: aisha.washington28@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://aisha-w.github.io" # the base hostname & protocol for your site
github_username: aisha-w

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
